#!/usr/bin/env python3
"""Generate data/streamline_packages.txt from the Kiro ISO package list.

Run automatically by up.sh. The Streamline page lets a user remove the optional
apps that shipped on the system, grouped by category. The category->package map
is the TIER 3 section of the Kiro ISO's packages.x86_64 — the packages already
marked "USER-CHANGEABLE / OPTIONAL ... safe to add or remove". TIER 1 (frozen)
and TIER 2 (core) are deliberately never included, so the page can never offer a
package that would break the system.

Source resolution order:
  1. $KIRO_ISO_PACKAGES if set
  2. ~/KIRO-ISO-CALAMARES/kiro-iso/archiso/packages.x86_64 (local checkout)
  3. GitHub raw fallback (best effort — the repo may be private)
If none resolve, the existing committed data file is left untouched.

Output preserves the "###  CATEGORY" headers verbatim so the file stays
human-readable and 1:1 with the source. Commented-out package lines (#pkg) are
deliberately-disabled options and are skipped.
"""

import os
import re
import sys
import urllib.request
from os import path

SCRIPT_DIR = path.dirname(path.realpath(__file__))
APP_DIR = path.join(SCRIPT_DIR, "usr/share/archlinux-tweak-tool")
OUTPUT = path.join(APP_DIR, "data/streamline_packages.txt")

LOCAL_CANDIDATES = [
    os.environ.get("KIRO_ISO_PACKAGES", ""),
    path.expanduser("~/KIRO-ISO-CALAMARES/kiro-iso/archiso/packages.x86_64"),
]
GITHUB_RAW = "https://raw.githubusercontent.com/kirodubes/kiro-iso/main/archiso/packages.x86_64"

TIER3_MARKER = "TIER 3"
END_MARKER = "PERSONAL_REPO"
CATEGORY = re.compile(r"^###\s+(\S.*)$")
# A full-width banner rule line (a comment line of nothing but '#').
RULE = re.compile(r"^#{5,}\s*$")


def info(msg):
    print(f"[streamline-list] {msg}")


def warn(msg):
    print(f"[streamline-list] WARN: {msg}", file=sys.stderr)


def read_source():
    """Return the packages.x86_64 text from the first source that resolves, else None."""
    for candidate in LOCAL_CANDIDATES:
        if candidate and path.isfile(candidate):
            info(f"Reading {candidate}")
            with open(candidate, encoding="utf-8") as f:
                return f.read()
    try:
        info(f"Local source not found — trying {GITHUB_RAW}")
        with urllib.request.urlopen(GITHUB_RAW, timeout=15) as resp:
            return resp.read().decode("utf-8")
    except Exception as error:
        warn(f"GitHub fallback failed: {error}")
        return None


def _find_tier3_start(lines):
    """Return the index after the TIER 3 banner, or None.

    The banner is the TIER 3 line directly under a full-width '#' rule line —
    this distinguishes the real section header from the file's intro block,
    which merely *describes* all three tiers in prose (not under a rule line).
    """
    for i, line in enumerate(lines):
        if TIER3_MARKER in line and i > 0 and RULE.match(lines[i - 1]):
            return i + 1
    return None


def parse_tier3(text):
    """Return [(category, [pkg, ...]), ...] for TIER 3 only, headers in source order."""
    lines = text.splitlines()
    start = _find_tier3_start(lines)
    if start is None:
        return []
    categories = []
    current = None
    for line in lines[start:]:
        if END_MARKER in line:
            break
        match = CATEGORY.match(line)
        if match:
            current = (match.group(1).strip(), [])
            categories.append(current)
            continue
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if current is not None:
            current[1].append(stripped)
    return [(name, pkgs) for name, pkgs in categories if pkgs]


def write_output(categories):
    lines = ["# Generated by gen-streamline-list.py — do not edit; edit the Kiro ISO packages.x86_64 TIER 3", ""]
    for name, pkgs in categories:
        lines.append(f"###  {name}")
        lines.extend(pkgs)
        lines.append("")
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main():
    text = read_source()
    if text is None:
        warn(f"No source available — leaving {OUTPUT} unchanged")
        return
    categories = parse_tier3(text)
    if not categories:
        warn("Parsed 0 categories from TIER 3 — leaving existing file unchanged")
        return
    write_output(categories)
    total = sum(len(pkgs) for _, pkgs in categories)
    info(f"Wrote {len(categories)} categories, {total} packages to {OUTPUT}")


if __name__ == "__main__":
    main()
