# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================


def gui(self, Gtk, vboxstack_ai, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("AI Tools")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    # Section 1: Local LLM Runners
    hbox_section1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section1_label = Gtk.Label(xalign=0)
    hbox_section1_label.set_text("Local LLM Runners")
    hbox_section1_label.set_margin_start(10)
    hbox_section1_label.set_margin_top(15)
    hbox_section1_label.set_margin_bottom(10)
    hbox_section1.append(hbox_section1_label)

    # 1. Ollama
    hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_ollama = Gtk.Label(xalign=0)
    self.lbl_ai_ollama.set_markup("Ollama - Local LLM runner" + (" <b>installed</b>" if fn.path.exists("/usr/bin/ollama") else ""))
    self.btn_ai_ollama = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/ollama") else "Install")
    self.btn_ai_ollama.connect("clicked", self.on_click_ai_ollama)
    self.lbl_ai_ollama.set_margin_start(20)
    self.lbl_ai_ollama.set_margin_end(10)
    self.lbl_ai_ollama.set_hexpand(True)
    hbox1.append(self.lbl_ai_ollama)
    self.btn_ai_ollama.set_margin_start(10)
    self.btn_ai_ollama.set_margin_end(10)
    hbox1.append(self.btn_ai_ollama)

    # 2. Open WebUI
    hbox2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_webui = Gtk.Label(xalign=0)
    self.lbl_ai_webui.set_markup("Open WebUI - Browser UI for Ollama" + (" <b>installed</b>" if fn.path.exists("/usr/bin/open-webui") else ""))
    self.btn_ai_webui = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/open-webui") else "Install")
    self.btn_ai_webui.connect("clicked", self.on_click_ai_webui)
    self.lbl_ai_webui.set_margin_start(20)
    self.lbl_ai_webui.set_margin_end(10)
    self.lbl_ai_webui.set_hexpand(True)
    hbox2.append(self.lbl_ai_webui)
    self.btn_ai_webui.set_margin_start(10)
    self.btn_ai_webui.set_margin_end(10)
    hbox2.append(self.btn_ai_webui)

    # Section 2: CLI Coding Assistants
    hbox_section2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section2_label = Gtk.Label(xalign=0)
    hbox_section2_label.set_text("CLI Coding Assistants")
    hbox_section2_label.set_margin_start(10)
    hbox_section2_label.set_margin_top(15)
    hbox_section2_label.set_margin_bottom(10)
    hbox_section2.append(hbox_section2_label)

    # 3. Claude Code
    hbox3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_claude = Gtk.Label(xalign=0)
    self.lbl_ai_claude.set_markup("Claude Code - Anthropic CLI" + (" <b>installed</b>" if fn.path.exists("/usr/bin/claude") else ""))
    self.btn_ai_claude = Gtk.Button(label="Remove" if fn.path.exists("/usr/bin/claude") else "Install")
    self.btn_ai_claude.connect("clicked", self.on_click_ai_claude)
    self.lbl_ai_claude.set_margin_start(20)
    self.lbl_ai_claude.set_margin_end(10)
    self.lbl_ai_claude.set_hexpand(True)
    hbox3.append(self.lbl_ai_claude)
    self.btn_ai_claude.set_margin_start(10)
    self.btn_ai_claude.set_margin_end(10)
    hbox3.append(self.btn_ai_claude)

    # 4. Aider
    hbox4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_aider = Gtk.Label(xalign=0)
    aider_installed = fn.path.exists("/usr/bin/aider") or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/aider")
    self.lbl_ai_aider.set_markup("Aider - AI pair programming" + (" <b>installed</b>" if aider_installed else ""))
    self.btn_ai_aider = Gtk.Button(label="Remove" if aider_installed else "Install")
    self.btn_ai_aider.connect("clicked", self.on_click_ai_aider)
    self.lbl_ai_aider.set_margin_start(20)
    self.lbl_ai_aider.set_margin_end(10)
    self.lbl_ai_aider.set_hexpand(True)
    hbox4.append(self.lbl_ai_aider)
    self.btn_ai_aider.set_margin_start(10)
    self.btn_ai_aider.set_margin_end(10)
    hbox4.append(self.btn_ai_aider)

    # 5. OpenAI Codex CLI
    hbox5 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_codex = Gtk.Label(xalign=0)
    codex_installed = fn.path.exists("/usr/bin/codex") or fn.path.exists("/usr/local/bin/codex") or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/codex")
    self.lbl_ai_codex.set_markup("OpenAI Codex CLI" + (" <b>installed</b>" if codex_installed else ""))
    self.btn_ai_codex = Gtk.Button(label="Remove" if codex_installed else "Install")
    self.btn_ai_codex.connect("clicked", self.on_click_ai_codex)
    self.lbl_ai_codex.set_margin_start(20)
    self.lbl_ai_codex.set_margin_end(10)
    self.lbl_ai_codex.set_hexpand(True)
    hbox5.append(self.lbl_ai_codex)
    self.btn_ai_codex.set_margin_start(10)
    self.btn_ai_codex.set_margin_end(10)
    hbox5.append(self.btn_ai_codex)

    # 6. Google Gemini CLI
    hbox6 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    self.lbl_ai_gemini = Gtk.Label(xalign=0)
    gemini_installed = fn.path.exists("/usr/bin/gemini") or fn.path.exists("/usr/local/bin/gemini") or fn.path.exists(f"/home/{fn.sudo_username}/.local/bin/gemini")
    self.lbl_ai_gemini.set_markup("Google Gemini CLI" + (" <b>installed</b>" if gemini_installed else ""))
    self.btn_ai_gemini = Gtk.Button(label="Remove" if gemini_installed else "Install")
    self.btn_ai_gemini.connect("clicked", self.on_click_ai_gemini)
    self.lbl_ai_gemini.set_margin_start(20)
    self.lbl_ai_gemini.set_margin_end(10)
    self.lbl_ai_gemini.set_hexpand(True)
    hbox6.append(self.lbl_ai_gemini)
    self.btn_ai_gemini.set_margin_start(10)
    self.btn_ai_gemini.set_margin_end(10)
    hbox6.append(self.btn_ai_gemini)

    # Section 3: Web Apps
    hbox_section3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section3_label = Gtk.Label(xalign=0)
    hbox_section3_label.set_text("Web Apps")
    hbox_section3_label.set_margin_start(10)
    hbox_section3_label.set_margin_top(15)
    hbox_section3_label.set_margin_bottom(10)
    hbox_section3.append(hbox_section3_label)

    # 7. ChatGPT
    hbox7 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox7_label = Gtk.Label(xalign=0)
    hbox7_label.set_text("ChatGPT")
    btn7 = Gtk.Button(label="Open")
    btn7.connect("clicked", self.on_click_ai_chatgpt)
    hbox7_label.set_margin_start(20)
    hbox7_label.set_margin_end(10)
    hbox7_label.set_hexpand(True)
    hbox7.append(hbox7_label)
    btn7.set_margin_start(10)
    btn7.set_margin_end(10)
    hbox7.append(btn7)

    # 8. Claude.ai
    hbox8 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox8_label = Gtk.Label(xalign=0)
    hbox8_label.set_text("Claude.ai")
    btn8 = Gtk.Button(label="Open")
    btn8.connect("clicked", self.on_click_ai_claude_web)
    hbox8_label.set_margin_start(20)
    hbox8_label.set_margin_end(10)
    hbox8_label.set_hexpand(True)
    hbox8.append(hbox8_label)
    btn8.set_margin_start(10)
    btn8.set_margin_end(10)
    hbox8.append(btn8)

    # 9. Google Gemini
    hbox9 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox9_label = Gtk.Label(xalign=0)
    hbox9_label.set_text("Google Gemini")
    btn9 = Gtk.Button(label="Open")
    btn9.connect("clicked", self.on_click_ai_gemini_web)
    hbox9_label.set_margin_start(20)
    hbox9_label.set_margin_end(10)
    hbox9_label.set_hexpand(True)
    hbox9.append(hbox9_label)
    btn9.set_margin_start(10)
    btn9.set_margin_end(10)
    hbox9.append(btn9)

    # 10. Perplexity
    hbox10 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox10_label = Gtk.Label(xalign=0)
    hbox10_label.set_text("Perplexity")
    btn10 = Gtk.Button(label="Open")
    btn10.connect("clicked", self.on_click_ai_perplexity)
    hbox10_label.set_margin_start(20)
    hbox10_label.set_margin_end(10)
    hbox10_label.set_hexpand(True)
    hbox10.append(hbox10_label)
    btn10.set_margin_start(10)
    btn10.set_margin_end(10)
    hbox10.append(btn10)

    # Section 4: Image Generation
    hbox_section4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section4_label = Gtk.Label(xalign=0)
    hbox_section4_label.set_text("Image Generation")
    hbox_section4_label.set_margin_start(10)
    hbox_section4_label.set_margin_top(15)
    hbox_section4_label.set_margin_bottom(10)
    hbox_section4.append(hbox_section4_label)

    # 11. DALL-E 3
    hbox11 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox11_label = Gtk.Label(xalign=0)
    hbox11_label.set_text("DALL-E 3")
    btn11 = Gtk.Button(label="Open")
    btn11.connect("clicked", self.on_click_ai_dalle)
    hbox11_label.set_margin_start(20)
    hbox11_label.set_margin_end(10)
    hbox11_label.set_hexpand(True)
    hbox11.append(hbox11_label)
    btn11.set_margin_start(10)
    btn11.set_margin_end(10)
    hbox11.append(btn11)

    # 12. Midjourney
    hbox12 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox12_label = Gtk.Label(xalign=0)
    hbox12_label.set_text("Midjourney")
    btn12 = Gtk.Button(label="Open")
    btn12.connect("clicked", self.on_click_ai_midjourney)
    hbox12_label.set_margin_start(20)
    hbox12_label.set_margin_end(10)
    hbox12_label.set_hexpand(True)
    hbox12.append(hbox12_label)
    btn12.set_margin_start(10)
    btn12.set_margin_end(10)
    hbox12.append(btn12)

    # 13. Leonardo.ai
    hbox13 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox13_label = Gtk.Label(xalign=0)
    hbox13_label.set_text("Leonardo.ai")
    btn13 = Gtk.Button(label="Open")
    btn13.connect("clicked", self.on_click_ai_leonardo)
    hbox13_label.set_margin_start(20)
    hbox13_label.set_margin_end(10)
    hbox13_label.set_hexpand(True)
    hbox13.append(hbox13_label)
    btn13.set_margin_start(10)
    btn13.set_margin_end(10)
    hbox13.append(btn13)

    # 14. Adobe Firefly
    hbox14 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox14_label = Gtk.Label(xalign=0)
    hbox14_label.set_text("Adobe Firefly")
    btn14 = Gtk.Button(label="Open")
    btn14.connect("clicked", self.on_click_ai_firefly)
    hbox14_label.set_margin_start(20)
    hbox14_label.set_margin_end(10)
    hbox14_label.set_hexpand(True)
    hbox14.append(hbox14_label)
    btn14.set_margin_start(10)
    btn14.set_margin_end(10)
    hbox14.append(btn14)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_ai.append(hbox_title)
    vboxstack_ai.append(hbox_sep)
    vboxstack_ai.append(hbox_section1)
    vboxstack_ai.append(hbox1)
    vboxstack_ai.append(hbox2)
    vboxstack_ai.append(hbox_section2)
    vboxstack_ai.append(hbox3)
    vboxstack_ai.append(hbox4)
    vboxstack_ai.append(hbox5)
    vboxstack_ai.append(hbox6)
    vboxstack_ai.append(hbox_section3)
    vboxstack_ai.append(hbox7)
    vboxstack_ai.append(hbox8)
    vboxstack_ai.append(hbox9)
    vboxstack_ai.append(hbox10)
    vboxstack_ai.append(hbox_section4)
    vboxstack_ai.append(hbox11)
    vboxstack_ai.append(hbox12)
    vboxstack_ai.append(hbox13)
    vboxstack_ai.append(hbox14)
