# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools

import icons


def _make_folder_preview(Gtk, GdkPixbuf, Gdk, base_dir, subdir, token):
    """Return a small Image of the theme's folder icon (generated by gen-icons-list.py)."""
    img = Gtk.Image()
    try:
        pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(f"{base_dir}/images/{subdir}/{token}.png", 24, 24)
        img.set_from_paintable(Gdk.Texture.new_for_pixbuf(pixbuf))
    except Exception:
        pass
    img.set_pixel_size(24)
    img.set_valign(Gtk.Align.CENTER)
    return img


def _icon_label(set_key, token):
    """Compact checkbox label: drop the set prefix; mark the base theme."""
    prefix = icons.ICON_SETS[set_key]["prefix"]
    short = token[len(prefix):] if token.startswith(prefix) else token
    if token == icons.ICON_SETS[set_key]["base_token"]:
        return f"{short} (base)"
    return short


def _build_icon_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, set_key, family_labels):
    """Build one sub-tab for an icon set; All/None/family/install/remove are scoped to its tokens."""
    families = icons.ICON_SETS[set_key]["families"]
    checks = getattr(self, icons.ICON_SETS[set_key]["checks"])

    vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
    vbox.set_hexpand(True)
    vbox.set_vexpand(True)

    info = Gtk.Label(xalign=0)
    info.set_markup(
        "Select the packages you want to install or remove, then click the appropriate button.\n"
        'Ensure that the <b>Nemesis repository is enabled</b> — see the "Pacman" tab for details.'
    )
    info.set_margin_start(10)
    info.set_margin_end(10)
    vbox.append(info)

    present_families = [f for f in family_labels if families.get(f)]
    if not present_families:
        placeholder = Gtk.Label(xalign=0)
        placeholder.set_markup("<i>Coming soon — to be added later.</i>")
        placeholder.set_margin_start(10)
        placeholder.set_margin_top(10)
        vbox.append(placeholder)
        return vbox

    vbox_families = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
    vbox_families.set_hexpand(True)
    for family_label in present_families:
        lbl_family = Gtk.Label(xalign=0)
        lbl_family.set_markup(f"<b>{family_label}</b>")
        lbl_family.set_margin_start(10)
        lbl_family.set_margin_top(6)
        vbox_families.append(lbl_family)

        flowbox_family = Gtk.FlowBox()
        flowbox_family.set_valign(Gtk.Align.START)
        flowbox_family.set_max_children_per_line(4)
        flowbox_family.set_selection_mode(Gtk.SelectionMode.NONE)
        flowbox_family.set_column_spacing(4)
        flowbox_family.set_row_spacing(4)
        flowbox_family.set_hexpand(True)
        flowbox_family.set_margin_start(10)
        flowbox_family.set_margin_end(10)

        for entry in families[family_label]:
            token = entry["token"]
            row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
            row.append(_make_folder_preview(Gtk, GdkPixbuf, Gdk, base_dir, set_key, token))
            checkbox = Gtk.CheckButton(label=_icon_label(set_key, token))
            checks[token] = checkbox
            row.append(checkbox)
            flowbox_family.append(row)

        vbox_families.append(flowbox_family)
    vbox.append(vbox_families)

    tab_tokens = icons._icon_tab_tokens(set_key, present_families)

    hbox_select_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    lbl_prompt = Gtk.Label()
    lbl_prompt.set_text("Choose the icon theme(s)")
    lbl_prompt.set_margin_start(10)
    lbl_prompt.set_margin_end(10)
    hbox_select_label.append(lbl_prompt)
    vbox.append(hbox_select_label)

    hbox_select_buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    hbox_select_buttons.set_margin_start(10)
    hbox_select_buttons.set_margin_end(10)
    btn_all = Gtk.Button(label="All")
    btn_all.connect("clicked", functools.partial(icons.on_icons_all, self, set_key, tab_tokens))
    btn_none = Gtk.Button(label="None")
    btn_none.connect("clicked", functools.partial(icons.on_icons_none, self, set_key, tab_tokens))
    for btn in (btn_all, btn_none):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_select_buttons.append(btn)
    vbox.append(hbox_select_buttons)

    hbox_family_buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    hbox_family_buttons.set_halign(Gtk.Align.CENTER)
    hbox_family_buttons.set_margin_start(10)
    hbox_family_buttons.set_margin_end(10)
    for family_label in present_families:
        btn_family = Gtk.Button(label=family_label)
        btn_family.connect(
            "clicked", functools.partial(icons.on_icons_family, self, set_key, family_label, tab_tokens)
        )
        btn_family.set_margin_start(6)
        btn_family.set_margin_end(6)
        hbox_family_buttons.append(btn_family)
    vbox.append(hbox_family_buttons)

    hbox_actions = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_actions.set_halign(Gtk.Align.CENTER)
    btn_find = Gtk.Button(label="Show the installed icon themes")
    btn_find.connect("clicked", functools.partial(icons.on_icons_find, self, set_key, tab_tokens))
    btn_install = Gtk.Button(label="Install the selected icon themes")
    btn_install.connect("clicked", functools.partial(icons.on_icons_install, self, set_key, tab_tokens))
    for btn in (btn_find, btn_install):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_actions.append(btn)
    vbox.append(hbox_actions)

    hbox_remove = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_remove.set_halign(Gtk.Align.CENTER)
    btn_remove = Gtk.Button(label="Uninstall the selected icon themes")
    btn_remove.connect("clicked", functools.partial(icons.on_icons_remove, self, set_key, tab_tokens))
    btn_remove.set_margin_start(10)
    btn_remove.set_margin_end(10)
    hbox_remove.append(btn_remove)
    vbox.append(hbox_remove)

    return vbox


def _build_icon_page(self, Gtk, GdkPixbuf, Gdk, vboxstack, base_dir, set_key, title, tabs):
    """Build a full Icons page: title + separator + a StackSwitcher of family sub-tabs."""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_title = Gtk.Label(xalign=0)
    lbl_title.set_text(title)
    lbl_title.set_name("title")
    hbox_title.append(lbl_title)

    hbox_separator = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_separator.append(hseparator)

    vbox_main = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
    vbox_main.set_hexpand(True)
    vbox_main.set_vexpand(True)

    stack = Gtk.Stack()
    stack.set_transition_type(Gtk.StackTransitionType.SLIDE_UP_DOWN)
    stack.set_transition_duration(350)
    stack.set_hhomogeneous(False)
    stack.set_vhomogeneous(False)
    stack.set_hexpand(True)
    stack.set_vexpand(True)

    stack_switcher = Gtk.StackSwitcher()
    stack_switcher.set_orientation(Gtk.Orientation.HORIZONTAL)
    stack_switcher.set_stack(stack)

    setattr(self, icons.ICON_SETS[set_key]["checks"], {})
    for index, (tab_title, family_labels) in enumerate(tabs.items()):
        child = _build_icon_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, set_key, family_labels)
        stack.add_titled(child, f"{set_key}_{index}", tab_title)

    vbox_main.append(stack_switcher)
    vbox_main.append(stack)

    vboxstack.append(hbox_title)
    vboxstack.append(hbox_separator)
    vboxstack.append(vbox_main)


def gui_surfn(self, Gtk, GdkPixbuf, vboxstack, _att, fn, base_dir):
    """Build the Icons Surfn page: Surfn / Surfn-Mint / Surfn-Tela sub-tabs."""
    from gi.repository import Gdk

    _build_icon_page(self, Gtk, GdkPixbuf, Gdk, vboxstack, base_dir, "surfn", "Surfn", icons.SURFN_TABS)


def gui_neocandy(self, Gtk, GdkPixbuf, vboxstack, _att, fn, base_dir):
    """Build the Icons Neo Candy page: Neo Candy / Neo Candy Mint / Neo Candy Tela sub-tabs."""
    from gi.repository import Gdk

    _build_icon_page(self, Gtk, GdkPixbuf, Gdk, vboxstack, base_dir, "neocandy", "Neo Candy", icons.NEOCANDY_TABS)
