# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools

import icons


def _make_folder_preview(Gtk, GdkPixbuf, Gdk, base_dir, subdir, token):
    """Return a small Image of the theme's folder icon (generated by gen-icons-list.py)."""
    img = Gtk.Image()
    try:
        pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(f"{base_dir}/images/{subdir}/{token}.png", 24, 24)
        img.set_from_paintable(Gdk.Texture.new_for_pixbuf(pixbuf))
    except Exception:
        pass
    img.set_pixel_size(24)
    img.set_valign(Gtk.Align.CENTER)
    return img


def _build_surfn_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, family_labels):
    """Build one Surfn sub-tab; its All/None/family/install/remove actions are scoped to its tokens."""
    vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=10)
    vbox.set_hexpand(True)
    vbox.set_vexpand(True)

    info = Gtk.Label(xalign=0)
    info.set_markup(
        "Select the packages you want to install or remove, then click the appropriate button.\n"
        'Ensure that the <b>Nemesis repository is enabled</b> — see the "Pacman" tab for details.'
    )
    info.set_margin_start(10)
    info.set_margin_end(10)
    vbox.append(info)

    present_families = [f for f in family_labels if icons.SURFN_FAMILIES.get(f)]
    if not present_families:
        placeholder = Gtk.Label(xalign=0)
        placeholder.set_markup("<i>Coming soon — to be added later.</i>")
        placeholder.set_margin_start(10)
        placeholder.set_margin_top(10)
        vbox.append(placeholder)
        return vbox

    vbox_families = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
    vbox_families.set_hexpand(True)
    for family_label in present_families:
        lbl_family = Gtk.Label(xalign=0)
        lbl_family.set_markup(f"<b>{family_label}</b>")
        lbl_family.set_margin_start(10)
        lbl_family.set_margin_top(6)
        vbox_families.append(lbl_family)

        flowbox_family = Gtk.FlowBox()
        flowbox_family.set_valign(Gtk.Align.START)
        flowbox_family.set_max_children_per_line(4)
        flowbox_family.set_selection_mode(Gtk.SelectionMode.NONE)
        flowbox_family.set_column_spacing(4)
        flowbox_family.set_row_spacing(4)
        flowbox_family.set_hexpand(True)
        flowbox_family.set_margin_start(10)
        flowbox_family.set_margin_end(10)

        for entry in icons.SURFN_FAMILIES[family_label]:
            token = entry["token"]
            if token == "surfn":
                label = "surfn (base)"
            else:
                label = token[len("surfn-"):] if token.startswith("surfn-") else token
            row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
            row.append(_make_folder_preview(Gtk, GdkPixbuf, Gdk, base_dir, "surfn", token))
            checkbox = Gtk.CheckButton(label=label)
            self.surfn_checkboxes[token] = checkbox
            row.append(checkbox)
            flowbox_family.append(row)

        vbox_families.append(flowbox_family)
    vbox.append(vbox_families)

    tab_tokens = icons._tab_tokens(present_families)

    hbox_select_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    lbl_prompt = Gtk.Label()
    lbl_prompt.set_text("Choose the icon theme(s)")
    lbl_prompt.set_margin_start(10)
    lbl_prompt.set_margin_end(10)
    hbox_select_label.append(lbl_prompt)
    vbox.append(hbox_select_label)

    hbox_select_buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    hbox_select_buttons.set_margin_start(10)
    hbox_select_buttons.set_margin_end(10)
    btn_all = Gtk.Button(label="All")
    btn_all.connect("clicked", functools.partial(icons.on_click_att_surfn_theming_all_selection, self, tab_tokens))
    btn_none = Gtk.Button(label="None")
    btn_none.connect("clicked", functools.partial(icons.on_click_att_surfn_theming_none_selection, self, tab_tokens))
    for btn in (btn_all, btn_none):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_select_buttons.append(btn)
    vbox.append(hbox_select_buttons)

    hbox_family_buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    hbox_family_buttons.set_halign(Gtk.Align.CENTER)
    hbox_family_buttons.set_margin_start(10)
    hbox_family_buttons.set_margin_end(10)
    for family_label in present_families:
        btn_family = Gtk.Button(label=family_label)
        btn_family.connect(
            "clicked", functools.partial(icons.on_click_att_surfn_family_selection, self, family_label, tab_tokens)
        )
        btn_family.set_margin_start(6)
        btn_family.set_margin_end(6)
        hbox_family_buttons.append(btn_family)
    vbox.append(hbox_family_buttons)

    hbox_actions = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_actions.set_halign(Gtk.Align.CENTER)
    btn_find = Gtk.Button(label="Show the installed icon themes")
    btn_find.connect("clicked", functools.partial(icons.on_find_att_surfn_icon_themes_clicked, self, tab_tokens))
    btn_install = Gtk.Button(label="Install the selected icon themes")
    btn_install.connect("clicked", functools.partial(icons.on_install_att_surfn_icon_themes_clicked, self, tab_tokens))
    for btn in (btn_find, btn_install):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_actions.append(btn)
    vbox.append(hbox_actions)

    hbox_remove = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_remove.set_halign(Gtk.Align.CENTER)
    btn_remove = Gtk.Button(label="Uninstall the selected icon themes")
    btn_remove.connect("clicked", functools.partial(icons.on_remove_att_surfn_icon_themes_clicked, self, tab_tokens))
    btn_remove.set_margin_start(10)
    btn_remove.set_margin_end(10)
    hbox_remove.append(btn_remove)
    vbox.append(hbox_remove)

    return vbox


def _page_scaffold(Gtk, vboxstack, title):
    """Append the standard page title + separator, returning the vbox_main content box."""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    lbl_title = Gtk.Label(xalign=0)
    lbl_title.set_text(title)
    lbl_title.set_name("title")
    hbox_title.append(lbl_title)

    hbox_separator = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_separator.append(hseparator)

    vbox_main = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
    vbox_main.set_hexpand(True)
    vbox_main.set_vexpand(True)

    vboxstack.append(hbox_title)
    vboxstack.append(hbox_separator)
    vboxstack.append(vbox_main)
    return vbox_main


def gui_surfn(self, Gtk, GdkPixbuf, vboxstack, _att, fn, base_dir):
    """Build the Icons Surfn page: Surfn / Surfn-Mint / Surfn-Tela sub-tabs."""
    from gi.repository import Gdk

    vbox_main = _page_scaffold(Gtk, vboxstack, "Surfn")

    stack = Gtk.Stack()
    stack.set_transition_type(Gtk.StackTransitionType.SLIDE_UP_DOWN)
    stack.set_transition_duration(350)
    stack.set_hhomogeneous(False)
    stack.set_vhomogeneous(False)
    stack.set_hexpand(True)
    stack.set_vexpand(True)

    stack_switcher = Gtk.StackSwitcher()
    stack_switcher.set_orientation(Gtk.Orientation.HORIZONTAL)
    stack_switcher.set_stack(stack)

    self.surfn_checkboxes = {}
    stack.add_titled(_build_surfn_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, icons.SURFN_TABS["Surfn"]), "surfn", "Surfn")
    stack.add_titled(
        _build_surfn_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, icons.SURFN_TABS["Surfn-Mint"]), "surfn_mint", "Surfn-Mint"
    )
    stack.add_titled(
        _build_surfn_tab(self, Gtk, GdkPixbuf, Gdk, base_dir, icons.SURFN_TABS["Surfn-Tela"]), "surfn_tela", "Surfn-Tela"
    )

    vbox_main.append(stack_switcher)
    vbox_main.append(stack)


def gui_neocandy(self, Gtk, GdkPixbuf, vboxstack, _att, fn, base_dir):
    """Build the Icons Neo Candy page: a folder-preview checkbox grid + install/remove actions."""
    from gi.repository import Gdk

    vbox_main = _page_scaffold(Gtk, vboxstack, "Neo Candy")

    info = Gtk.Label(xalign=0)
    info.set_markup(
        "Select the packages you want to install or remove, then click the appropriate button.\n"
        'Ensure that the <b>Nemesis repository is enabled</b> — see the "Pacman" tab for details.'
    )
    info.set_margin_start(10)
    info.set_margin_end(10)
    vbox_main.append(info)

    self.neocandy_checkboxes = {}
    flowbox = Gtk.FlowBox()
    flowbox.set_valign(Gtk.Align.START)
    flowbox.set_max_children_per_line(3)
    flowbox.set_selection_mode(Gtk.SelectionMode.NONE)
    flowbox.set_column_spacing(4)
    flowbox.set_row_spacing(4)
    flowbox.set_hexpand(True)
    flowbox.set_margin_start(10)
    flowbox.set_margin_end(10)
    for entry in icons.NEOCANDY:
        token = entry["token"]
        row = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=6)
        row.append(_make_folder_preview(Gtk, GdkPixbuf, Gdk, base_dir, "neocandy", token))
        checkbox = Gtk.CheckButton(label=entry["label"])
        self.neocandy_checkboxes[token] = checkbox
        row.append(checkbox)
        flowbox.append(row)
    vbox_main.append(flowbox)

    hbox_select_label = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    lbl_prompt = Gtk.Label()
    lbl_prompt.set_text("Choose the icon theme(s)")
    lbl_prompt.set_margin_start(10)
    lbl_prompt.set_margin_end(10)
    hbox_select_label.append(lbl_prompt)
    vbox_main.append(hbox_select_label)

    hbox_select_buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
    hbox_select_buttons.set_margin_start(10)
    hbox_select_buttons.set_margin_end(10)
    btn_all = Gtk.Button(label="All")
    btn_all.connect("clicked", functools.partial(icons.on_click_neocandy_theming_all_selection, self))
    btn_none = Gtk.Button(label="None")
    btn_none.connect("clicked", functools.partial(icons.on_click_neocandy_theming_none_selection, self))
    for btn in (btn_all, btn_none):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_select_buttons.append(btn)
    vbox_main.append(hbox_select_buttons)

    hbox_actions = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_actions.set_halign(Gtk.Align.CENTER)
    btn_find = Gtk.Button(label="Show the installed packages")
    btn_find.connect("clicked", functools.partial(icons.on_find_neocandy_clicked, self))
    btn_install = Gtk.Button(label="Install the selected packages")
    btn_install.connect("clicked", functools.partial(icons.on_install_neocandy_clicked, self))
    for btn in (btn_find, btn_install):
        btn.set_margin_start(10)
        btn.set_margin_end(10)
        hbox_actions.append(btn)
    vbox_main.append(hbox_actions)

    hbox_remove = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_remove.set_halign(Gtk.Align.CENTER)
    btn_remove = Gtk.Button(label="Uninstall the selected packages")
    btn_remove.connect("clicked", functools.partial(icons.on_remove_neocandy_clicked, self))
    btn_remove.set_margin_start(10)
    btn_remove.set_margin_end(10)
    hbox_remove.append(btn_remove)
    vbox_main.append(hbox_remove)
