# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================

import functools
import log_callbacks


def gui(self, Gtk, vboxstack_logging, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("Investigate your logs")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    hbox_log1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log1_label = Gtk.Label(xalign=0)
    hbox_log1_label.set_text("View current boot journal")
    btn_log_current_boot = Gtk.Button(label="Open")
    btn_log_current_boot.connect("clicked", functools.partial(log_callbacks.on_click_log_current_boot, self))
    hbox_log1_label.set_margin_start(10)
    hbox_log1_label.set_margin_end(10)
    hbox_log1_label.set_hexpand(True)
    hbox_log1.append(hbox_log1_label)
    btn_log_current_boot.set_margin_start(10)
    btn_log_current_boot.set_margin_end(10)
    hbox_log1.append(btn_log_current_boot)

    hbox_log2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log2_label = Gtk.Label(xalign=0)
    hbox_log2_label.set_text("View previous boot journal")
    btn_log_prev_boot = Gtk.Button(label="Open")
    btn_log_prev_boot.connect("clicked", functools.partial(log_callbacks.on_click_log_prev_boot, self))
    hbox_log2_label.set_margin_start(10)
    hbox_log2_label.set_margin_end(10)
    hbox_log2_label.set_hexpand(True)
    hbox_log2.append(hbox_log2_label)
    btn_log_prev_boot.set_margin_start(10)
    btn_log_prev_boot.set_margin_end(10)
    hbox_log2.append(btn_log_prev_boot)

    hbox_log3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log3_label = Gtk.Label(xalign=0)
    hbox_log3_label.set_text("View journal errors (current boot)")
    btn_log_errors = Gtk.Button(label="Open")
    btn_log_errors.connect("clicked", functools.partial(log_callbacks.on_click_log_errors, self))
    hbox_log3_label.set_margin_start(10)
    hbox_log3_label.set_margin_end(10)
    hbox_log3_label.set_hexpand(True)
    hbox_log3.append(hbox_log3_label)
    btn_log_errors.set_margin_start(10)
    btn_log_errors.set_margin_end(10)
    hbox_log3.append(btn_log_errors)

    hbox_log4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log4_label = Gtk.Label(xalign=0)
    hbox_log4_label.set_text("View recent journal (last 20 minutes)")
    btn_log_recent = Gtk.Button(label="Open")
    btn_log_recent.connect("clicked", functools.partial(log_callbacks.on_click_log_recent, self))
    hbox_log4_label.set_margin_start(10)
    hbox_log4_label.set_margin_end(10)
    hbox_log4_label.set_hexpand(True)
    hbox_log4.append(hbox_log4_label)
    btn_log_recent.set_margin_start(10)
    btn_log_recent.set_margin_end(10)
    hbox_log4.append(btn_log_recent)

    hbox_log5 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log5_label = Gtk.Label(xalign=0)
    hbox_log5_label.set_text("View Xorg log")
    btn_log_xorg = Gtk.Button(label="Open")
    btn_log_xorg.connect("clicked", functools.partial(log_callbacks.on_click_log_xorg, self))
    hbox_log5_label.set_margin_start(10)
    hbox_log5_label.set_margin_end(10)
    hbox_log5_label.set_hexpand(True)
    hbox_log5.append(hbox_log5_label)
    btn_log_xorg.set_margin_start(10)
    btn_log_xorg.set_margin_end(10)
    hbox_log5.append(btn_log_xorg)

    hbox_log6 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log6_label = Gtk.Label(xalign=0)
    hbox_log6_label.set_text("View pacman log")
    btn_log_pacman = Gtk.Button(label="Open")
    btn_log_pacman.connect("clicked", functools.partial(log_callbacks.on_click_log_pacman, self))
    hbox_log6_label.set_margin_start(10)
    hbox_log6_label.set_margin_end(10)
    hbox_log6_label.set_hexpand(True)
    hbox_log6.append(hbox_log6_label)
    btn_log_pacman.set_margin_start(10)
    btn_log_pacman.set_margin_end(10)
    hbox_log6.append(btn_log_pacman)

    hbox_log7 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log7_label = Gtk.Label(xalign=0)
    hbox_log7_label.set_text("View X session errors (~/.xsession-errors or Xorg.0.log)")
    btn_log_xsession = Gtk.Button(label="Open")
    btn_log_xsession.connect("clicked", functools.partial(log_callbacks.on_click_log_xsession, self))
    hbox_log7_label.set_margin_start(10)
    hbox_log7_label.set_margin_end(10)
    hbox_log7_label.set_hexpand(True)
    hbox_log7.append(hbox_log7_label)
    btn_log_xsession.set_margin_start(10)
    btn_log_xsession.set_margin_end(10)
    hbox_log7.append(btn_log_xsession)

    hbox_log8 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log8_label = Gtk.Label(xalign=0)
    hbox_log8_label.set_text("Analyze boot performance (systemd-analyze blame)")
    btn_log_blame = Gtk.Button(label="Open")
    btn_log_blame.connect("clicked", functools.partial(log_callbacks.on_click_log_blame, self))
    hbox_log8_label.set_margin_start(10)
    hbox_log8_label.set_margin_end(10)
    hbox_log8_label.set_hexpand(True)
    hbox_log8.append(hbox_log8_label)
    btn_log_blame.set_margin_start(10)
    btn_log_blame.set_margin_end(10)
    hbox_log8.append(btn_log_blame)

    hbox_log9 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_log9_label = Gtk.Label(xalign=0)
    hbox_log9_label.set_text("View kernel ring buffer (dmesg)")
    btn_log_dmesg = Gtk.Button(label="Open")
    btn_log_dmesg.connect("clicked", functools.partial(log_callbacks.on_click_log_dmesg, self))
    hbox_log9_label.set_margin_start(10)
    hbox_log9_label.set_margin_end(10)
    hbox_log9_label.set_hexpand(True)
    hbox_log9.append(hbox_log9_label)
    btn_log_dmesg.set_margin_start(10)
    btn_log_dmesg.set_margin_end(10)
    hbox_log9.append(btn_log_dmesg)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_logging.append(hbox_title)
    vboxstack_logging.append(hbox_sep)
    vboxstack_logging.append(hbox_log1)
    vboxstack_logging.append(hbox_log2)
    vboxstack_logging.append(hbox_log3)
    vboxstack_logging.append(hbox_log4)
    vboxstack_logging.append(hbox_log5)
    vboxstack_logging.append(hbox_log6)
    vboxstack_logging.append(hbox_log7)
    vboxstack_logging.append(hbox_log8)
    vboxstack_logging.append(hbox_log9)
