# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================


def gui(self, Gtk, vboxstack_software, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("Software Installers")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    # Section 1: GUI Package Managers
    hbox_section1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section1_label = Gtk.Label(xalign=0)
    hbox_section1_label.set_text("GUI Package Managers")
    hbox_section1_label.set_margin_start(10)
    hbox_section1_label.set_margin_top(15)
    hbox_section1_label.set_margin_bottom(10)
    hbox_section1.append(hbox_section1_label)

    # 1. Pamac
    hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox1_label = Gtk.Label(xalign=0)
    hbox1_label.set_markup("Pamac Aur" + (" <b>installed</b>" if fn.path.exists("/usr/bin/pamac-manager") else ""))
    btn1 = Gtk.Button(label="Launch")
    btn1.connect("clicked", self.on_click_software_pamac)
    hbox1_label.set_margin_start(20)
    hbox1_label.set_margin_end(10)
    hbox1_label.set_hexpand(True)
    hbox1.append(hbox1_label)
    btn1.set_margin_start(10)
    btn1.set_margin_end(10)
    hbox1.append(btn1)

    # 2. Octopi
    hbox2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox2_label = Gtk.Label(xalign=0)
    hbox2_label.set_markup("Octopi - Qt package manager" + (" <b>installed</b>" if fn.path.exists("/usr/bin/octopi") else ""))
    btn2 = Gtk.Button(label="Launch")
    btn2.connect("clicked", self.on_click_software_octopi)
    hbox2_label.set_margin_start(20)
    hbox2_label.set_margin_end(10)
    hbox2_label.set_hexpand(True)
    hbox2.append(hbox2_label)
    btn2.set_margin_start(10)
    btn2.set_margin_end(10)
    hbox2.append(btn2)

    # 3. GNOME Software
    hbox3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox3_label = Gtk.Label(xalign=0)
    hbox3_label.set_markup("GNOME Software - GTK software center" + (" <b>installed</b>" if fn.path.exists("/usr/bin/gnome-software") else ""))
    btn3 = Gtk.Button(label="Launch")
    btn3.connect("clicked", self.on_click_software_gnome)
    hbox3_label.set_margin_start(20)
    hbox3_label.set_margin_end(10)
    hbox3_label.set_hexpand(True)
    hbox3.append(hbox3_label)
    btn3.set_margin_start(10)
    btn3.set_margin_end(10)
    hbox3.append(btn3)

    # 4. KDE Discover
    hbox4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox4_label = Gtk.Label(xalign=0)
    hbox4_label.set_markup("KDE Discover - KDE software center (pulls KDE deps)" + (" <b>installed</b>" if fn.path.exists("/usr/bin/plasma-discover") else ""))
    btn4 = Gtk.Button(label="Launch")
    btn4.connect("clicked", self.on_click_software_discover)
    hbox4_label.set_margin_start(20)
    hbox4_label.set_margin_end(10)
    hbox4_label.set_hexpand(True)
    hbox4.append(hbox4_label)
    btn4.set_margin_start(10)
    btn4.set_margin_end(10)
    hbox4.append(btn4)

    # 5. Bauh
    hbox5 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox5_label = Gtk.Label(xalign=0)
    hbox5_label.set_markup("Bauh - Multi-format package manager" + (" <b>installed</b>" if fn.path.exists("/usr/bin/bauh") else ""))
    btn5 = Gtk.Button(label="Launch")
    btn5.connect("clicked", self.on_click_software_bauh)
    hbox5_label.set_margin_start(20)
    hbox5_label.set_margin_end(10)
    hbox5_label.set_hexpand(True)
    hbox5.append(hbox5_label)
    btn5.set_margin_start(10)
    btn5.set_margin_end(10)
    hbox5.append(btn5)

    # Section 2: AUR Helpers
    hbox_section2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section2_label = Gtk.Label(xalign=0)
    hbox_section2_label.set_text("AUR Helpers")
    hbox_section2_label.set_margin_start(10)
    hbox_section2_label.set_margin_top(15)
    hbox_section2_label.set_margin_bottom(10)
    hbox_section2.append(hbox_section2_label)

    # 6. Yay-git
    hbox6 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox6_label = Gtk.Label(xalign=0)
    hbox6_label.set_markup("Yay-git - AUR helper (Go-based)" + (" <b>installed</b>" if fn.path.exists("/usr/bin/yay") else ""))
    btn6 = Gtk.Button(label="Install")
    btn6.connect("clicked", self.on_click_software_yay)
    hbox6_label.set_margin_start(20)
    hbox6_label.set_margin_end(10)
    hbox6_label.set_hexpand(True)
    hbox6.append(hbox6_label)
    btn6.set_margin_start(10)
    btn6.set_margin_end(10)
    hbox6.append(btn6)

    # 7. Paru-git
    hbox7 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox7_label = Gtk.Label(xalign=0)
    hbox7_label.set_markup("Paru-git - AUR helper (Rust-based)" + (" <b>installed</b>" if fn.path.exists("/usr/bin/paru") else ""))
    btn7 = Gtk.Button(label="Install")
    btn7.connect("clicked", self.on_click_software_paru)
    hbox7_label.set_margin_start(20)
    hbox7_label.set_margin_end(10)
    hbox7_label.set_hexpand(True)
    hbox7.append(hbox7_label)
    btn7.set_margin_start(10)
    btn7.set_margin_end(10)
    hbox7.append(btn7)

    # 8. Trizen
    hbox8 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox8_label = Gtk.Label(xalign=0)
    hbox8_label.set_markup("Trizen - AUR helper (Perl-based)" + (" <b>installed</b>" if fn.path.exists("/usr/bin/trizen") else ""))
    btn8 = Gtk.Button(label="Install")
    btn8.connect("clicked", self.on_click_software_trizen)
    hbox8_label.set_margin_start(20)
    hbox8_label.set_margin_end(10)
    hbox8_label.set_hexpand(True)
    hbox8.append(hbox8_label)
    btn8.set_margin_start(10)
    btn8.set_margin_end(10)
    hbox8.append(btn8)

    # 9. Pikaur-git
    hbox9 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox9_label = Gtk.Label(xalign=0)
    hbox9_label.set_markup("Pikaur-git - AUR helper (Python-based)" + (" <b>installed</b>" if fn.path.exists("/usr/bin/pikaur") else ""))
    btn9 = Gtk.Button(label="Install")
    btn9.connect("clicked", self.on_click_software_pikaur)
    hbox9_label.set_margin_start(20)
    hbox9_label.set_margin_end(10)
    hbox9_label.set_hexpand(True)
    hbox9.append(hbox9_label)
    btn9.set_margin_start(10)
    btn9.set_margin_end(10)
    hbox9.append(btn9)

    # Section 3: Flatpak / Snap / AppImage
    hbox_section3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section3_label = Gtk.Label(xalign=0)
    hbox_section3_label.set_text("Flatpak / Snap / AppImage")
    hbox_section3_label.set_margin_start(10)
    hbox_section3_label.set_margin_top(15)
    hbox_section3_label.set_margin_bottom(10)
    hbox_section3.append(hbox_section3_label)

    # 11. Flatpak
    hbox10 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox10_label = Gtk.Label(xalign=0)
    hbox10_label.set_text("Flatpak - Manage Flatpak apps")
    btn10 = Gtk.Button(label="Open")
    btn10.connect("clicked", self.on_click_software_flatpak)
    hbox10_label.set_margin_start(20)
    hbox10_label.set_margin_end(10)
    hbox10_label.set_hexpand(True)
    hbox10.append(hbox10_label)
    btn10.set_margin_start(10)
    btn10.set_margin_end(10)
    hbox10.append(btn10)

    # 12. Snapd
    hbox11 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox11_label = Gtk.Label(xalign=0)
    hbox11_label.set_text("Snapd - Manage Snap apps")
    btn11 = Gtk.Button(label="Open")
    btn11.connect("clicked", self.on_click_software_snapd)
    hbox11_label.set_margin_start(20)
    hbox11_label.set_margin_end(10)
    hbox11_label.set_hexpand(True)
    hbox11.append(hbox11_label)
    btn11.set_margin_start(10)
    btn11.set_margin_end(10)
    hbox11.append(btn11)

    # 13. AppImageLauncher
    hbox12 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox12_label = Gtk.Label(xalign=0)
    hbox12_label.set_text("App-manager - Manage AppImages")
    btn12 = Gtk.Button(label="Launch")
    btn12.connect("clicked", self.on_click_software_appimagelauncher)
    hbox12_label.set_margin_start(20)
    hbox12_label.set_margin_end(10)
    hbox12_label.set_hexpand(True)
    hbox12.append(hbox12_label)
    btn12.set_margin_start(10)
    btn12.set_margin_end(10)
    hbox12.append(btn12)

    # Section 4: TUI Package Tools
    hbox_section4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_section4_label = Gtk.Label(xalign=0)
    hbox_section4_label.set_text("TUI Package Tools")
    hbox_section4_label.set_margin_start(10)
    hbox_section4_label.set_margin_top(15)
    hbox_section4_label.set_margin_bottom(10)
    hbox_section4.append(hbox_section4_label)

    # 14. Pacseek
    hbox13 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox13_label = Gtk.Label(xalign=0)
    hbox13_label.set_text("Pacseek - TUI package searcher")
    btn13 = Gtk.Button(label="Open")
    btn13.connect("clicked", self.on_click_software_pacseek)
    hbox13_label.set_margin_start(20)
    hbox13_label.set_margin_end(10)
    hbox13_label.set_hexpand(True)
    hbox13.append(hbox13_label)
    btn13.set_margin_start(10)
    btn13.set_margin_end(10)
    hbox13.append(btn13)

    # 15. Pacui
    hbox14 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox14_label = Gtk.Label(xalign=0)
    hbox14_label.set_text("Pacui - TUI pacman wrapper")
    btn14 = Gtk.Button(label="Open")
    btn14.connect("clicked", self.on_click_software_pacui_open)
    hbox14_label.set_margin_start(20)
    hbox14_label.set_margin_end(10)
    hbox14_label.set_hexpand(True)
    hbox14.append(hbox14_label)
    btn14.set_margin_start(10)
    btn14.set_margin_end(10)
    hbox14.append(btn14)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_software.append(hbox_title)
    vboxstack_software.append(hbox_sep)
    vboxstack_software.append(hbox_section1)
    vboxstack_software.append(hbox1)
    vboxstack_software.append(hbox2)
    vboxstack_software.append(hbox3)
    vboxstack_software.append(hbox4)
    vboxstack_software.append(hbox5)
    vboxstack_software.append(hbox_section2)
    vboxstack_software.append(hbox6)
    vboxstack_software.append(hbox7)
    vboxstack_software.append(hbox8)
    vboxstack_software.append(hbox9)
    vboxstack_software.append(hbox_section3)
    vboxstack_software.append(hbox10)
    vboxstack_software.append(hbox11)
    vboxstack_software.append(hbox12)
    vboxstack_software.append(hbox_section4)
    vboxstack_software.append(hbox13)
    vboxstack_software.append(hbox14)
