# ============================================================
# Authors: Brad Heffernan - Erik Dubois - Cameron Percival
# ============================================================


def gui(self, Gtk, vboxstack_system, fn):
    """create a gui"""
    hbox_title = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox_title_label = Gtk.Label(xalign=0)
    hbox_title_label.set_text("Inspect your hardware and software")
    hbox_title_label.set_name("title")
    hbox_title_label.set_margin_start(10)
    hbox_title_label.set_margin_end(10)
    hbox_title.append(hbox_title_label)

    hbox_sep = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hseparator = Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL)
    hseparator.set_hexpand(True)
    hseparator.set_vexpand(False)
    hbox_sep.append(hseparator)

    # 1. CPU Info
    hbox1 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox1_label = Gtk.Label(xalign=0)
    hbox1_label.set_text("CPU Information")
    btn1 = Gtk.Button(label="View")
    btn1.connect("clicked", self.on_click_system_cpu)
    hbox1_label.set_margin_start(10)
    hbox1_label.set_margin_end(10)
    hbox1_label.set_hexpand(True)
    hbox1.append(hbox1_label)
    btn1.set_margin_start(10)
    btn1.set_margin_end(10)
    hbox1.append(btn1)

    # 2. Memory & Disk Usage
    hbox2 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox2_label = Gtk.Label(xalign=0)
    hbox2_label.set_text("Memory and Disk Usage")
    btn2 = Gtk.Button(label="View")
    btn2.connect("clicked", self.on_click_system_memory_disk)
    hbox2_label.set_margin_start(10)
    hbox2_label.set_margin_end(10)
    hbox2_label.set_hexpand(True)
    hbox2.append(hbox2_label)
    btn2.set_margin_start(10)
    btn2.set_margin_end(10)
    hbox2.append(btn2)

    # 3. Block Devices
    hbox3 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox3_label = Gtk.Label(xalign=0)
    hbox3_label.set_text("Block Devices (lsblk)")
    btn3 = Gtk.Button(label="View")
    btn3.connect("clicked", self.on_click_system_lsblk)
    hbox3_label.set_margin_start(10)
    hbox3_label.set_margin_end(10)
    hbox3_label.set_hexpand(True)
    hbox3.append(hbox3_label)
    btn3.set_margin_start(10)
    btn3.set_margin_end(10)
    hbox3.append(btn3)

    # 4. PCI Devices
    hbox4 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox4_label = Gtk.Label(xalign=0)
    hbox4_label.set_text("PCI Devices (lspci)")
    btn4 = Gtk.Button(label="View")
    btn4.connect("clicked", self.on_click_system_lspci)
    hbox4_label.set_margin_start(10)
    hbox4_label.set_margin_end(10)
    hbox4_label.set_hexpand(True)
    hbox4.append(hbox4_label)
    btn4.set_margin_start(10)
    btn4.set_margin_end(10)
    hbox4.append(btn4)

    # 5. USB Devices
    hbox5 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox5_label = Gtk.Label(xalign=0)
    hbox5_label.set_text("USB Devices (lsusb)")
    btn5 = Gtk.Button(label="View")
    btn5.connect("clicked", self.on_click_system_lsusb)
    hbox5_label.set_margin_start(10)
    hbox5_label.set_margin_end(10)
    hbox5_label.set_hexpand(True)
    hbox5.append(hbox5_label)
    btn5.set_margin_start(10)
    btn5.set_margin_end(10)
    hbox5.append(btn5)

    # 6. Loaded Kernel Modules
    hbox6 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox6_label = Gtk.Label(xalign=0)
    hbox6_label.set_text("Loaded Kernel Modules (lsmod)")
    btn6 = Gtk.Button(label="View")
    btn6.connect("clicked", self.on_click_system_lsmod)
    hbox6_label.set_margin_start(10)
    hbox6_label.set_margin_end(10)
    hbox6_label.set_hexpand(True)
    hbox6.append(hbox6_label)
    btn6.set_margin_start(10)
    btn6.set_margin_end(10)
    hbox6.append(btn6)

    # 7. Comprehensive Hardware
    hbox7 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox7_label = Gtk.Label(xalign=0)
    hbox7_label.set_text("Comprehensive Hardware Info (inxi)")
    btn7 = Gtk.Button(label="View")
    btn7.connect("clicked", self.on_click_system_inxi)
    hbox7_label.set_margin_start(10)
    hbox7_label.set_margin_end(10)
    hbox7_label.set_hexpand(True)
    hbox7.append(hbox7_label)
    btn7.set_margin_start(10)
    btn7.set_margin_end(10)
    hbox7.append(btn7)

    # 8. Hardware Summary
    hbox8 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox8_label = Gtk.Label(xalign=0)
    hbox8_label.set_text("Hardware Summary (hwinfo)")
    btn8 = Gtk.Button(label="View")
    btn8.connect("clicked", self.on_click_system_hwinfo)
    hbox8_label.set_margin_start(10)
    hbox8_label.set_margin_end(10)
    hbox8_label.set_hexpand(True)
    hbox8.append(hbox8_label)
    btn8.set_margin_start(10)
    btn8.set_margin_end(10)
    hbox8.append(btn8)

    # 9. Disk Partitions
    hbox9 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox9_label = Gtk.Label(xalign=0)
    hbox9_label.set_text("Disk Partitions (fdisk -l)")
    btn9 = Gtk.Button(label="View")
    btn9.connect("clicked", self.on_click_system_fdisk)
    hbox9_label.set_margin_start(10)
    hbox9_label.set_margin_end(10)
    hbox9_label.set_hexpand(True)
    hbox9.append(hbox9_label)
    btn9.set_margin_start(10)
    btn9.set_margin_end(10)
    hbox9.append(btn9)

    # 10. Filesystem Config
    hbox10 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox10_label = Gtk.Label(xalign=0)
    hbox10_label.set_text("Filesystem Configuration (fstab)")
    btn10 = Gtk.Button(label="View")
    btn10.connect("clicked", self.on_click_system_fstab)
    hbox10_label.set_margin_start(10)
    hbox10_label.set_margin_end(10)
    hbox10_label.set_hexpand(True)
    hbox10.append(hbox10_label)
    btn10.set_margin_start(10)
    btn10.set_margin_end(10)
    hbox10.append(btn10)

    # 11. System Overview
    hbox11 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox11_label = Gtk.Label(xalign=0)
    hbox11_label.set_text("System Overview (hostnamectl)")
    btn11 = Gtk.Button(label="View")
    btn11.connect("clicked", self.on_click_system_hostnamectl)
    hbox11_label.set_margin_start(10)
    hbox11_label.set_margin_end(10)
    hbox11_label.set_hexpand(True)
    hbox11.append(hbox11_label)
    btn11.set_margin_start(10)
    btn11.set_margin_end(10)
    hbox11.append(btn11)

    # 12. Locale & Timezone
    hbox12 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox12_label = Gtk.Label(xalign=0)
    hbox12_label.set_text("Locale and Timezone (localectl)")
    btn12 = Gtk.Button(label="View")
    btn12.connect("clicked", self.on_click_system_localectl)
    hbox12_label.set_margin_start(10)
    hbox12_label.set_margin_end(10)
    hbox12_label.set_hexpand(True)
    hbox12.append(hbox12_label)
    btn12.set_margin_start(10)
    btn12.set_margin_end(10)
    hbox12.append(btn12)

    # 13. Systemd Services
    hbox13 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox13_label = Gtk.Label(xalign=0)
    hbox13_label.set_text("Systemd Services")
    btn13 = Gtk.Button(label="View")
    btn13.connect("clicked", self.on_click_system_services)
    hbox13_label.set_margin_start(10)
    hbox13_label.set_margin_end(10)
    hbox13_label.set_hexpand(True)
    hbox13.append(hbox13_label)
    btn13.set_margin_start(10)
    btn13.set_margin_end(10)
    hbox13.append(btn13)

    # 14. System Services Enabled
    hbox14 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox14_label = Gtk.Label(xalign=0)
    hbox14_label.set_text("System Services Enabled")
    btn14 = Gtk.Button(label="View")
    btn14.connect("clicked", self.on_click_system_services_enabled)
    hbox14_label.set_margin_start(10)
    hbox14_label.set_margin_end(10)
    hbox14_label.set_hexpand(True)
    hbox14.append(hbox14_label)
    btn14.set_margin_start(10)
    btn14.set_margin_end(10)
    hbox14.append(btn14)

    # 15. Systemd Services Failed
    hbox15 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox15_label = Gtk.Label(xalign=0)
    hbox15_label.set_text("Systemd Services Failed")
    btn15 = Gtk.Button(label="View")
    btn15.connect("clicked", self.on_click_system_services_failed)
    hbox15_label.set_margin_start(10)
    hbox15_label.set_margin_end(10)
    hbox15_label.set_hexpand(True)
    hbox15.append(hbox15_label)
    btn15.set_margin_start(10)
    btn15.set_margin_end(10)
    hbox15.append(btn15)

    # 16. Systemd Timers Enabled
    hbox16 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox16_label = Gtk.Label(xalign=0)
    hbox16_label.set_text("Systemd Timers Enabled")
    btn16 = Gtk.Button(label="View")
    btn16.connect("clicked", self.on_click_system_timers_enabled)
    hbox16_label.set_margin_start(10)
    hbox16_label.set_margin_end(10)
    hbox16_label.set_hexpand(True)
    hbox16.append(hbox16_label)
    btn16.set_margin_start(10)
    btn16.set_margin_end(10)
    hbox16.append(btn16)

    # 17. Kernel Ring Buffer
    hbox17 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox17_label = Gtk.Label(xalign=0)
    hbox17_label.set_text("Kernel Ring Buffer (dmesg)")
    btn17 = Gtk.Button(label="View")
    btn17.connect("clicked", self.on_click_system_dmesg)
    hbox17_label.set_margin_start(10)
    hbox17_label.set_margin_end(10)
    hbox17_label.set_hexpand(True)
    hbox17.append(hbox17_label)
    btn17.set_margin_start(10)
    btn17.set_margin_end(10)
    hbox17.append(btn17)

    # 18. GParted
    hbox18 = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    hbox18_label = Gtk.Label(xalign=0)
    hbox18_label.set_text("Inspect with GParted (partition manager)")
    btn18 = Gtk.Button(label="Launch")
    btn18.connect("clicked", self.on_click_system_gparted)
    hbox18_label.set_margin_start(10)
    hbox18_label.set_margin_end(10)
    hbox18_label.set_hexpand(True)
    hbox18.append(hbox18_label)
    btn18.set_margin_start(10)
    btn18.set_margin_end(10)
    hbox18.append(btn18)

    # ======================================================================
    #                       VBOX STACK
    # ======================================================================

    vboxstack_system.append(hbox_title)
    vboxstack_system.append(hbox_sep)
    vboxstack_system.append(hbox1)
    vboxstack_system.append(hbox2)
    vboxstack_system.append(hbox3)
    vboxstack_system.append(hbox4)
    vboxstack_system.append(hbox5)
    vboxstack_system.append(hbox6)
    vboxstack_system.append(hbox7)
    vboxstack_system.append(hbox8)
    vboxstack_system.append(hbox9)
    vboxstack_system.append(hbox10)
    vboxstack_system.append(hbox11)
    vboxstack_system.append(hbox12)
    vboxstack_system.append(hbox13)
    vboxstack_system.append(hbox14)
    vboxstack_system.append(hbox15)
    vboxstack_system.append(hbox16)
    vboxstack_system.append(hbox17)
    vboxstack_system.append(hbox18)
